site_name: DSC ADGITM BLOGS
site_description: 'Blog Site of DSC ADGITM'
site_author: 'DSC ADGITM'
docs_dir: docs/
repo_name: 'Adgitmdsc/dsc-blog'
repo_url: 'https://github.com/Adgitmdsc/dsc-blog'
nav:
    - Home: index.md
theme:
  name: 'material'

extra_css: [extra.css]
