name: Hello world on release

on:
  pull_request:
    types: [opened, closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world! PR is: $GITHUB_REF $GITHUB_SHA
